//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        public string email_type_rcd { get; set; }
        public System.Guid person_id { get; set; }
        public string email_address { get; set; }
        public bool primary_flag { get; set; }
        public System.Guid lu_user_id { get; set; }
        public System.DateTime lu_updated { get; set; }
    
        public virtual person person { get; set; }
    }
}
