//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeandDoctorEntities : DbContext
    {
        public EmployeeandDoctorEntities()
            : base("name=EmployeeandDoctorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<job_type> job_type { get; set; }
        public virtual DbSet<employee_formatted_name_iview_nl_view> employee_formatted_name_iview_nl_view { get; set; }
        public virtual DbSet<employee_info_view> employee_info_view { get; set; }
        public virtual DbSet<employment_nl_view> employment_nl_view { get; set; }
    }
}
