//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_info_view
    {
        public int employee_nr { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public string alternate_code { get; set; }
        public Nullable<System.DateTime> termination_date { get; set; }
        public string special_privileges { get; set; }
        public string old_employee_id { get; set; }
        public bool admitting_privilege_flag { get; set; }
        public bool request_patient_record_flag { get; set; }
        public System.Guid person_id { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<System.DateTime> date_of_death { get; set; }
        public string sex_rcd { get; set; }
        public string first_name_e { get; set; }
        public string middle_name_e { get; set; }
        public string last_name_e { get; set; }
        public string common_name_e { get; set; }
        public string title_e { get; set; }
        public string suffix_e { get; set; }
        public string first_name_l { get; set; }
        public string middle_name_l { get; set; }
        public string last_name_l { get; set; }
        public string common_name_l { get; set; }
        public string title_l { get; set; }
        public string suffix_l { get; set; }
        public string display_name_format { get; set; }
        public string list_name_format { get; set; }
        public string race_rcd { get; set; }
        public string primary_language_rcd { get; set; }
    }
}
