//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeUserEntities : DbContext
    {
        public EmployeeUserEntities()
            : base("name=EmployeeUserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<employee_formatted_name_iview> employee_formatted_name_iview { get; set; }
        public virtual DbSet<employee_info_view> employee_info_view { get; set; }
    }
}
