//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employment_nl_view
    {
        public System.Guid employee_id { get; set; }
        public System.DateTime effective_from_date { get; set; }
        public string company_code { get; set; }
        public string professional_staff_cat_rcd { get; set; }
        public string clocking_status_code { get; set; }
        public string job_type_code { get; set; }
        public int job_type_level_nr { get; set; }
        public string employee_status_rcd { get; set; }
        public string employee_type_rcd { get; set; }
        public string job_title_code { get; set; }
        public Nullable<System.DateTime> effective_until_date { get; set; }
        public string comments { get; set; }
        public System.Guid lu_user_id { get; set; }
        public System.DateTime lu_updated { get; set; }
        public System.Guid costcentre_id { get; set; }
        public short job_grade_nr { get; set; }
        public short job_grade_level_nr { get; set; }
        public string admitting_status_rcd { get; set; }
        public string doctor_status_rcd { get; set; }
        public string work_hours_per_week_rcd { get; set; }
        public System.Guid position_id { get; set; }
        public string position_status_rcd { get; set; }
        public int work_percentage { get; set; }
        public string employment_reason_rcd { get; set; }
        public System.Guid work_place_id { get; set; }
        public System.Guid department_id { get; set; }
    }
}
