//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public System.Guid employee_id { get; set; }
        public string company_code { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public int employee_nr { get; set; }
        public string alternate_code { get; set; }
        public Nullable<System.DateTime> termination_date { get; set; }
        public string special_privileges { get; set; }
        public string confidential_comments { get; set; }
        public string old_employee_id { get; set; }
        public System.Guid lu_user_id { get; set; }
        public System.DateTime lu_updated { get; set; }
        public string pin { get; set; }
        public Nullable<System.Guid> bank_account_id { get; set; }
        public string comment_e { get; set; }
        public string comment_l { get; set; }
        public bool admitting_privilege_flag { get; set; }
        public bool request_patient_record_flag { get; set; }
        public string employee_termination_reason_rcd { get; set; }
    }
}
