//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_type
    {
        public string job_type_code { get; set; }
        public string name_l { get; set; }
        public string name_e { get; set; }
        public string job_category_code { get; set; }
        public Nullable<int> minimum_benefit_package { get; set; }
        public Nullable<int> maximum_benefit_package { get; set; }
        public Nullable<decimal> average_cost_per_month { get; set; }
        public System.Guid lu_user_id { get; set; }
        public System.DateTime lu_updated { get; set; }
        public bool active_flag { get; set; }
        public Nullable<short> seq_num { get; set; }
        public Nullable<int> standard_work_day_minutes { get; set; }
        public Nullable<int> days_off_per_month { get; set; }
        public string clinical_staff_role_rcd { get; set; }
    }
}
