//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_hospital_usage
    {
        public string hospital_code { get; set; }
        public System.Guid patient_id { get; set; }
        public bool patient_record_owner_flag { get; set; }
        public Nullable<System.Guid> lu_user_id { get; set; }
        public Nullable<System.DateTime> lu_updated { get; set; }
        public string visible_patient_id { get; set; }
        public Nullable<System.DateTime> last_actual_visit_date_time { get; set; }
        public string reverse_visible_patient_id { get; set; }
    }
}
