//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatientUserEntities : DbContext
    {
        public PatientUserEntities()
            : base("name=PatientUserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<email> email { get; set; }
        public virtual DbSet<patient_hospital_usage> patient_hospital_usage { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<person_formatted_name_iview> person_formatted_name_iview { get; set; }
    }
}
