//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.email = new HashSet<email>();
        }
    
        public System.Guid person_id { get; set; }
        public string occupation_type_rcd { get; set; }
        public string occupation_status_rcd { get; set; }
        public string primary_language_rcd { get; set; }
        public string race_rcd { get; set; }
        public string marital_status_rcd { get; set; }
        public string religion_rcd { get; set; }
        public string occupation_rcd { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string nationality_rcd { get; set; }
        public string occupation_other { get; set; }
        public string student_type_rcd { get; set; }
        public string sex_rcd { get; set; }
        public Nullable<System.DateTime> death_date_time { get; set; }
        public string birth_place { get; set; }
        public Nullable<short> multiple_birth_order_number { get; set; }
        public Nullable<short> birth_order_number { get; set; }
        public string military_status { get; set; }
        public Nullable<System.Guid> lu_user_id { get; set; }
        public Nullable<System.DateTime> lu_updated { get; set; }
        public string electronic_id { get; set; }
        public Nullable<System.Guid> photo_id { get; set; }
        public string name_status_rcd { get; set; }
        public bool test_flag { get; set; }
        public string residence_country_rcd { get; set; }
        public string functional_domain_rcd { get; set; }
        public string father_birth_place { get; set; }
        public Nullable<int> number_of_children { get; set; }
        public string localization_print_culture_rcd { get; set; }
        public string residency_status_rcd { get; set; }
        public string military_status_rcd { get; set; }
        public bool date_of_birth_estimated_flag { get; set; }
    
        public virtual ICollection<email> email { get; set; }
    }
}
