//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webportal_patient_diagnosis
    {
        public System.Guid patient_medical_coding_id { get; set; }
        public System.Guid patient_visit_id { get; set; }
        public string diagnosis_type_rcd { get; set; }
        public string diagnosis_type { get; set; }
        public string coding_system_type_rcd { get; set; }
        public string coding_system_type { get; set; }
        public string coding_type_rcd { get; set; }
        public string coding_type { get; set; }
        public string coding_system_rcd { get; set; }
        public string code { get; set; }
        public string coding_name { get; set; }
        public string coding_free_text { get; set; }
        public string diagnosis { get; set; }
        public string diagnosis_comment { get; set; }
        public string coding_status_rcd { get; set; }
        public string coding_status { get; set; }
        public Nullable<System.DateTime> recorded_at_date_time { get; set; }
        public Nullable<System.DateTime> inactive_date_time { get; set; }
        public bool primary_flag { get; set; }
        public bool current_visit_diagnosis_flag { get; set; }
        public bool active_flag { get; set; }
        public Nullable<long> rank { get; set; }
    }
}
