//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class webportal_patient_info
    {
        public System.Guid person_id { get; set; }
        public string hospital_nr { get; set; }
        public string last_name_l { get; set; }
        public string first_name_l { get; set; }
        public string middle_name_l { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<int> age { get; set; }
        public string gender_rcd { get; set; }
        public string gender { get; set; }
    }
}
