//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webportal_patient_allergies_new
    {
        public System.Guid patient_adverse_reaction_cause_id { get; set; }
        public System.Guid patient_id { get; set; }
        public string cause { get; set; }
        public string reaction { get; set; }
        public string reaction_cause_status { get; set; }
    }
}
