//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webportal_patient_medication
    {
        public System.Guid note_id { get; set; }
        public System.Guid patient_id { get; set; }
        public System.Guid scope_type_rid { get; set; }
        public string scope_type { get; set; }
        public string details { get; set; }
        public string reason_type_rcd { get; set; }
        public System.DateTime note_date { get; set; }
        public bool active_flag { get; set; }
        public Nullable<System.DateTime> inactivate_date_time { get; set; }
    }
}
