//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webportal_patient_prev_hospitalization
    {
        public System.Guid patient_id { get; set; }
        public Nullable<System.DateTime> visit_start_date_time { get; set; }
        public Nullable<System.DateTime> visit_end_date_time { get; set; }
        public string visit_type { get; set; }
        public string primary_service { get; set; }
    }
}
