//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webportal_patient_diagnosis
    {
        public System.Guid patient_id { get; set; }
        public string coding_type_rcd { get; set; }
        public string coding_type { get; set; }
        public string coding_system_rcd { get; set; }
        public string code { get; set; }
        public string diagnosis { get; set; }
        public Nullable<System.DateTime> recorded_at_date_time { get; set; }
        public bool active_flag { get; set; }
    }
}
