//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class webportal_patient_allergies
    {
        public System.Guid patient_id { get; set; }
        [DisplayFormat(ConvertEmptyStringToNull = true, NullDisplayText = "No Details found")]
        public string allergen { get; set; }
        [DisplayFormat(ConvertEmptyStringToNull = true, NullDisplayText = "No Details found")]
        public string allergy_status { get; set; }
        public string adverse_reaction_name { get; set; }
        public string adverse_reaction_free_text { get; set; }
        public string adverse_reaction { get; set; }
    }
}
